vim.wo.number = true
-- vim.wo.relativenumber = false
vim.opt.mouse = ""
-- vim.g.encoding = "utf-8"
vim.o.fileencodings = "ucs-bom,utf-8,gb2312,cp936,gb18030,big5,euc-jp,euc-kr,latin1"
vim.o.tabstop = 4
vim.o.softtabstop = 4
vim.o.shiftwidth = 4
vim.o.autoindent = true